### ISSUE TITLE
Fix input/output file parsing to account for date prefix

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-web#21]
See below; search for additional cases
https://github.com/Electrostatics/apbs-web/blob/19d59d85ef24a300966d05e3f0317f383e56c9ef/src/body/jobstatus.js#L424

Relates to Electrostatics/apbs-aws#64

**Comment by mmacduff** [comment]
3dmol needs to include date path @Eo300

**Comment by Eo300** [comment]
I thought this was fixed in #23. Which environment are you encountering this @mmacduff ?

**Comment by mmacduff** [comment]
@Eo300 looks like we lost the aws branch that dev and test was built on?

**Comment by Eo300** [comment]
Just restored the `aws` branch, @mmacduff. Lmk if it things still look awry

**Comment by Eo300** [comment]
Closed via #22 and #23
